---
title: "Final Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(readxl)
library(pander)
library(ggplot2)
library(stargazer)
library(multcomp)

data_pn <- read_excel("Final_simp.xlsx")
data_md <- read_excel("Turkey Madison Project Data.xlsx")
```

### Create Variables
```{r}
data_pnbr <- dplyr::select(data_pn,country, year, Trend, rgdpe, pop)

data_br <- data_pnbr %>% mutate(DV2 = ifelse(year >= 2003,1,0))

data_br <- data_br %>%
  mutate(SplineBreak2 = (Trend - 53)*DV2)

data_br <- data_br %>%
  mutate(gdppc = rgdpe/pop)
  
```

### Implement First Regression
```{r}
model1 <- lm(log(gdppc)~Trend+DV2+Trend*DV2,data=data_br)

#pander(summary(model1))

summary(model1)
```

#### Graph
```{r, warning=FALSE}
predicted_df1 <- data.frame(gdppc_prd = predict(model1, data_br), year=data_br$year)

ggplot(data_br, aes(x=year,y=log(gdppc))) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=gdppc_prd, colour = "Predicted"),data = predicted_df1) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Level of the log of GDP per capita")


ggplot(data_br, aes(x=year,y=gdppc)) +
  geom_point() + geom_smooth(method = "lm")
#  geom_line(color='red',data = predicted_df1, aes(x=year, y=gdppc_prd))
  
```

#### Spline Method
```{r}
spline_model <- lm(log(gdppc)~Trend+SplineBreak2,data=data_br)

pander(summary(spline_model))
```

#### Graph
```{r, warning=FALSE}
predicted_df2 <- data.frame(gdppc_prd2 = predict(spline_model, data_br), year=data_br$year)

ggplot(data_br, aes(x=year,y=log(gdppc))) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=gdppc_prd2, colour = "Predicted"),data = predicted_df2) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Level of the log of GDP per capita (Spline)")

```

### Three Breaks
```{r}
data_br <- data_br %>% mutate(DV1 = ifelse(year >= 1980,1,0))

data_br <- data_br %>%
  mutate(SplineBreak1 = (Trend - 27)*DV1)

model2 <- lm(log(gdppc)~Trend+DV1+Trend*DV1+DV2+Trend*DV2,data=data_br)

summary(model2)

predicted_df1_1 <- data.frame(gdppc_prd = predict(model2, data_br), year=data_br$year)

ggplot(data_br, aes(x=year,y=log(gdppc))) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=gdppc_prd, colour = "Predicted"),data = predicted_df1_1) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Level of the log of GDP per capita")

```
### Is the growth in the final period significnatly different than the first?
```{r}
multcomp::glht(model2, linfct = c("Trend:DV1 + Trend:DV2 = 0")) %>% summary
```

#### Using Madison Data
```{r}
data_md <- data_md %>% mutate(DV2 = ifelse(year >= 1980,1,0))

data_md <- data_md %>%
  mutate(SplineBreak2 = (Trend - 27)*DV2)

data_md <- data_md %>% mutate(DV3 = ifelse(year >= 2003,1,0))

data_md <- data_md %>%
  mutate(SplineBreak3 = (Trend - 53)*DV3)

data_md <- data_md %>% mutate(DV1 = ifelse(year >= 1939,1,0))

data_md <- data_md %>%
  mutate(SplineBreak1 = (Trend - 16)*DV1)

data_md1950 <- data_md %>% filter(year >= "1950")

model_md1 <- lm(log(gdppc)~Trend+DV1+Trend*DV1+DV2+Trend*DV2+DV3+Trend*DV3,data=data_md)

spline_model_md1 <- lm(log(gdppc)~Trend+SplineBreak1+SplineBreak2+SplineBreak3,data=data_md)

model_md1950 <- lm(log(gdppc)~Trend+DV2+Trend*DV2+DV3+Trend*DV3,data=data_md1950)

#summary(model_md1)
summary(model_md1950)

predicted_df1_md <- data.frame(gdppc_prd = predict(model_md1, data_md), year=data_md$year)

ggplot(data_md, aes(x=year,y=log(gdppc))) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=gdppc_prd, colour = "Predicted"),data = predicted_df1_md) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Level of the log of GDP per capita")

predicted_df1_md1950 <- data.frame(gdppc_prd = predict(model_md1950, data_md1950), year=data_md1950$year)

ggplot(data_md1950, aes(x=year,y=log(gdppc))) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=gdppc_prd, colour = "Predicted"),data = predicted_df1_md1950) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Level of the log of GDP per capita")

predicted_df2_md <- data.frame(gdppc_prd2 = predict(spline_model_md1, data_md), year=data_md$year)

ggplot(data_md, aes(x=year,y=log(gdppc))) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=gdppc_prd2, colour = "Predicted"),data = predicted_df2_md) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Level of the log of GDP per capita (Spline)")
```

### Other Variables
```{r}
data_pned <- dplyr::select(data_pn, country, year, Trend, rgdpe, pop, hc, cn, ctfp)

#data_ed <- data_pned %>% mutate(DV2 = ifelse(year >= 2003,1,0))

data_ed <- data_pned %>% mutate(DV1 = ifelse(year >= 1980,1,0),DV2 = ifelse(year >= 2003,1,0) )

#data_ed <- data_ed %>%
 # mutate(SplineBreak2 = (Trend - 53)*DV2)

data_ed <- data_ed %>%
  mutate(gdppc = rgdpe/pop)
```

```{r}
model_ed <- lm(gdppc~hc+cn+ctfp,data=data_ed)

pander(summary(model_ed))
```

```{r}
model_ctfp <- lm(ctfp~Trend+DV1+Trend*DV1+DV2+Trend*DV2,data=data_ed)
model_hc <- lm(hc~Trend+DV1+Trend*DV1+DV2+Trend*DV2,data=data_ed)
model_cn <- lm(cn~Trend+DV1+Trend*DV1+DV2+Trend*DV2,data=data_ed)

stargazer(model_ctfp,model_hc,model_cn,
           type = "text", 
          report=('vc*pt'),
          keep.stat = c("n","rsq","adj.rsq"), 
          notes.append = FALSE)
```

```{r}
predicted_df_ed1 <- data.frame(hc_prd = predict(model_hc, data_ed), year=data_ed$year)

ggplot(data_ed, aes(x=year,y=hc)) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=hc_prd, colour = "Predicted"),data = predicted_df_ed1) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Human Capital")

predicted_df_ed2 <- data.frame(cn_prd = predict(model_cn, data_ed), year=data_ed$year)

ggplot(data_ed, aes(x=year,y=cn)) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=cn_prd, colour = "Predicted"),data = predicted_df_ed2) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Capital Stock")

ggplot(data_ed, aes(x=year,y=log(cn))) +
  geom_point(aes(colour= "Actual")) +
  geom_line(aes(x=year, y=log(cn_prd), colour = "Predicted"),data = predicted_df_ed2) +
  scale_colour_manual("",
                      values = c("Actual"="black", "Predicted"="red")) +
  labs(title = "Capital Stock")
```